########################
## Author: Mengjuei Hsieh
language: cpp
dist: trusty
sudo: false
group: beta
#
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
#      - george-edison55-precise-backports
    packages:
       - gcc-4.9
       - g++-4.9
       - gfortran-4.9
#before_cache: true
#cache: true
#before_install: true
install:
    - bin/travisbuild.sh
#before_script: true
script:
        - bin/travistest.sh
#after_script: true
