########################
## Author: Mengjuei Hsieh
language: cpp
dist: trusty
sudo: false
group: beta
#
before_cache: true
cache: true
before_install: true
install:
    - bin/travisbuild.sh
before_script: true
script:
        - bin/travistest.sh
after_script: true
