########################
## Author: Mengjuei Hsieh
#language: cpp
#distro: trusty
#sudo: false
##
#before_cache: true
#cache: true
#before_install: true
#install:
#    - bin/travisbuild.sh
#before_script: true
#script:
#        - bin/travistest.sh
#after_script: true
language: ruby
rvm:
  - 2.2
  - jruby
  - rbx-2
